// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModelMissingMapping.CompiledModels
{
    public partial class MyContextModel
    {
        partial void Initialize()
        {
            var blog = BlogEntityType.Create(this);

            BlogEntityType.CreateAnnotations(blog);

            AddAnnotation("ProductVersion", "7.0.11");
        }
    }
}
